package battle.ai;

public enum FindLockAction {

	NO_AUTO_LOCK, LOCK_LINKED_ENEMYS, LOCK_LINKED_ENEMYS_INRANGE, LOCK_ENEMYS_INRANGE, LOCK_LOCK_OF_LINKED_FRIENDS, LOCK_LOCK_OF_LINKED_FRIENDS_INRANGE, LOCK_LOCK_OF_FRIENDS_INRANGE

}
